### ISSUE TITLE
Create Article job listing component

### ISSUE THREAD

**Issue by SabinaHrabinova** [bratislava/marianum.sk#357]
For the Job Vacancies content type, we would need to create an Article job listing component in Strapi that will separate the content uploaded within the Articles section. 

We will use this component on the new /actuals/careers page

Example: 

The same process we chose on the For Media page. 

Open image-20230731-133326.png
image-20230731-133326.png
![Uploading image-20230815-210712.png…]()

**Comment by radoslavzeman** [comment]
Already implemented
